[project]
name = "interval-flow-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=6.29.5",
    "polars>=1.30.0",
    "python-dotenv>=1.1.0",
]
